version: '3'

services:
  client:
    build: ./nuxtdir
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: yarn run dev

  server:
    build: ./server
    ports:
      - 8888:8888
    volumes:
      - ./server:/api
